name: Dis Randevu Takip

on:
  schedule:
    - cron: "*/25 * * * *"  # 25 dakikada bir
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Paketler
        run: pip install requests beautifulsoup4

      - name: Kontrol
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check_randevu.py
